using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;
using TakOne.Domain.Products.Entities;
using TakOne.SharedKernel.Common;
using TakOne.SharedKernel.ValueObjects;
using TakOne.Testing;
using TakOne.Testing.Builders;
using Xunit;

namespace TakOne.Domain.Tests.Products;

/// <summary>
/// Property-based / fuzz tests for the <see cref="Product"/> aggregate's
/// stock-management methods. Each test asserts an INVARIANT holds over
/// 50+ random (initialStock, quantity) inputs generated by Bogus with a
/// FIXED seed (<c>Randomizer.Seed = new Random(67890)</c>) — so test runs
/// are deterministic and reproducible.
///
/// INVARIANTS VERIFIED:
///   1. IncreaseStock(q) for any q ≥ 1 increases StockQuantity by q —
///      i.e. final stock == initialStock + q.
///   2. DecreaseStock(q) for any q in [1, initialStock] decreases
///      StockQuantity by q — final stock == initialStock - q.
///   3. DecreaseStock(q) for any q > initialStock throws DomainException.
///   4. AdjustStockTo(q) for any q ≥ 1 sets StockQuantity = q.
///   5. AdjustStockTo(0) throws DomainException — the guard rejects q ≤ 0
///      regardless of the path that called it.
///   6. SetStock(0) is valid (DeactivateProduct flow): StockQuantity == 0
///      with no exception thrown.
///   7. SetStock(q) for any q < 0 throws DomainException.
///
/// DISCOVERY: The task spec implied `AdjustStockTo(0)` may or may not
/// reject; the actual SUT throws on q ≤ 0 ("Stock quantity must be greater
/// than zero. To make it zero, deactivate the product instead."). `SetStock`
/// does NOT share that strict guard — `SetStock(0)` succeeds while
/// `AdjustStockTo(0)` throws. The two methods exist on purpose: SetStock
/// is the "manual adjustment" UI surface; AdjustStockTo is the staff "Set
/// stock" feature path which deliberately forbids zero (staff must use
/// DeactivateProduct instead — defense in depth).
/// </summary>
public class ProductStockPropertyTests
{
    private const int FixedSeed = 67890;
    private const int SampleCount = 50;



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 50 random (initialStock, increaseAmount) pairs for the IncreaseStock
    // invariant. initialStock in [0, 1000], increaseAmount in [1, MaxInt/2]
    // (capped at 1_000_000 to keep arithmetic int-safe and avoid overflow
    // surprises when added to initialStock).
    public static IEnumerable<object[]> RandomIncreasePairs()
    {
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(0, 1000),       // initialStock
                faker.Random.Int(1, 1_000_000)  // increaseAmount
            })
            .ToList();
    }

    // 50 random (initialStock, decreaseAmount) pairs where decreaseAmount
    // ≤ initialStock (so the decrease succeeds).
    public static IEnumerable<object[]> RandomSafeDecreasePairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var initial = faker.Random.Int(1, 1000); // ≥1 so we can decrease ≥1
                var decrease = faker.Random.Int(1, initial);
                return new object[] { initial, decrease };
            })
            .ToList();
    }

    // 50 random (initialStock, decreaseAmount) pairs where decreaseAmount
    // > initialStock (so the decrease throws).
    public static IEnumerable<object[]> RandomOverDecreasePairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var initial = faker.Random.Int(0, 1000);
                // decrease must be > initial (so 0..initial → use initial+1..initial+1000).
                var decrease = faker.Random.Int(initial + 1, initial + 1000);
                return new object[] { initial, decrease };
            })
            .ToList();
    }

    // 50 random positive quantities for the AdjustStockTo happy-path invariant.
    public static IEnumerable<object[]> RandomPositiveQuantities()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(1, 100000) })
            .ToList();
    }

    // 50 "zero attempts" — the parameter is unused (the test always passes
    // 0); the index just multiplies the test count to exercise the
    // always-throws contract across many invocations. Indices 0..49 are
    // unique so xUnit doesn't dedupe them.
    public static IEnumerable<object[]> RandomZeroAttempts()
    {
        return Enumerable.Range(0, SampleCount).Select(i => new object[] { i }).ToList();
    }

    // 50 random negative quantities for the SetStock(q < 0) invariant.
    public static IEnumerable<object[]> RandomNegativeQuantities()
    {
        Randomizer.Seed = new Random(FixedSeed + 4);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(-1_000_000, -1) })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: IncreaseStock(q) for any q ≥ 1 increases StockQuantity by
    // exactly q — for any random (initialStock, q). The guard rejects q ≤ 0
    // elsewhere; this test exercises the success path.
    [Theory]
    [MemberData(nameof(RandomIncreasePairs))]
    public void ProductIncreaseStock_AddsToStockQuantity_HoldsForRandomPairs(int initialStock, int increaseAmount)
    {
        // Arrange — fresh Product with the random initial stock.
        var product = new ProductBuilder().WithStock(initialStock).Build();
        var expected = initialStock + increaseAmount;

        // Act
        product.IncreaseStock(increaseAmount);

        // Assert — StockQuantity is exactly initial + q (no off-by-one).
        product.StockQuantity.Should().Be(expected);
    }

    // Property: DecreaseStock(q) for any q in [1, initialStock] decreases
    // StockQuantity by exactly q — for any random (initialStock, q) where
    // the decrease is safe (q ≤ initialStock).
    [Theory]
    [MemberData(nameof(RandomSafeDecreasePairs))]
    public void ProductDecreaseStock_SubtractsFromStockQuantity_HoldsForRandomPairs(int initialStock, int decreaseAmount)
    {
        // Arrange — fresh Product with the random initial stock.
        var product = new ProductBuilder().WithStock(initialStock).Build();
        var expected = initialStock - decreaseAmount;

        // Act
        product.DecreaseStock(decreaseAmount);

        // Assert — StockQuantity is exactly initial - q.
        product.StockQuantity.Should().Be(expected);
    }

    // Property: DecreaseStock(q) for any q > initialStock throws
    // DomainException — the "insufficient stock" guard fires regardless
    // of how much over the available quantity q is.
    [Theory]
    [MemberData(nameof(RandomOverDecreasePairs))]
    public void ProductDecreaseStock_WhenOverAvailable_Throws_HoldsForRandomPairs(int initialStock, int decreaseAmount)
    {
        // Arrange — fresh Product with the random initial stock.
        var product = new ProductBuilder().WithStock(initialStock).Build();

        // Act
        var act = () => product.DecreaseStock(decreaseAmount);

        // Assert — the insufficient-stock guard fires.
        act.Should().Throw<DomainException>()
            .WithMessage("Insufficient stock to remove the specified quantity.");
    }

    // Property: AdjustStockTo(q) for any q ≥ 1 sets StockQuantity = q —
    // the absolute-set semantics of the staff "Set stock" feature.
    [Theory]
    [MemberData(nameof(RandomPositiveQuantities))]
    public void ProductAdjustStockTo_SetsStockQuantity_HoldsForRandomQuantities(int quantity)
    {
        // Arrange — fresh Product with an arbitrary initial stock (we'll
        // override it). 10 is a safe default that doesn't bias the test.
        var product = new ProductBuilder().WithStock(10).Build();

        // Act
        product.AdjustStockTo(quantity);

        // Assert — StockQuantity is exactly q (replaces, not adds).
        product.StockQuantity.Should().Be(quantity);
    }

    // Property: AdjustStockTo(0) always throws DomainException — the
    // guard rejects q ≤ 0 regardless of the call site (the staff "Set
    // stock" UI feature requires strictly positive stock; staff must use
    // DeactivateProduct to zero out stock). The unused `int _` parameter
    // exists only to drive 50 invocations of the same constant-zero call
    // across test IDs (the index varies so xUnit doesn't dedupe).
    [Theory]
    [MemberData(nameof(RandomZeroAttempts))]
    public void ProductAdjustStockTo_Zero_Throws_HoldsForRandomZeroAttempts(int _)
    {
        // Arrange — fresh Product with an arbitrary initial stock.
        var product = new ProductBuilder().WithStock(10).Build();

        // Act — AdjustStockTo(0) is the forbidden staff-UI path.
        var act = () => product.AdjustStockTo(0);

        // Assert — the strict positive-only guard fires.
        act.Should().Throw<DomainException>()
            .WithMessage("Stock quantity must be greater than zero. To make it zero, deactivate the product instead.");
    }

    // Property: SetStock(0) is valid (the DeactivateProduct flow's call
    // site) — for any Product, SetStock(0) sets StockQuantity = 0 with NO
    // exception thrown. This is the symmetric counterpart to AdjustStockTo(0)
    // throwing — SetStock allows zero (because the Deactivation flow needs
    // it), AdjustStockTo forbids zero (because staff UI shouldn't reach it
    // through the Adjust path). The unused `int _` parameter exists only to
    // drive 50 invocations across test IDs.
    [Theory]
    [MemberData(nameof(RandomZeroAttempts))]
    public void ProductSetStock_Zero_IsValid_HoldsForRandomZeroAttempts(int _)
    {
        // Arrange — fresh Product with a positive initial stock (so we
        // actually see the change to zero on the assertion below).
        var product = new ProductBuilder().WithStock(50).Build();

        // Act — SetStock(0) is the deactivation flow's call site.
        product.SetStock(0);

        // Assert — no exception thrown; StockQuantity is exactly 0.
        product.StockQuantity.Should().Be(0);
    }

    // Property: SetStock(q) for any q < 0 throws DomainException — the
    // negative-stock guard fires on the manual-adjustment path too
    // (defense-in-depth: the validator would have rejected this earlier,
    // but the domain never trusts the caller).
    [Theory]
    [MemberData(nameof(RandomNegativeQuantities))]
    public void ProductSetStock_WhenNegative_Throws_HoldsForRandomNegatives(int negative)
    {
        // Arrange — fresh Product with an arbitrary initial stock.
        var product = new ProductBuilder().WithStock(10).Build();

        // Act
        var act = () => product.SetStock(negative);

        // Assert — the negative-stock guard fires.
        act.Should().Throw<DomainException>()
            .WithMessage("Stock quantity cannot be negative.");
    }
}
