using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;
using TakOne.SharedKernel.Common;
using Xunit;

namespace TakOne.SharedKernel.Tests.Common;

/// <summary>
/// Property-based / fuzz tests for the <see cref="PaginatedResult{T}"/>
/// type — the pagination wrapper used by all paginated queries in the
/// Application layer.
///
/// Each test asserts an INVARIANT holds over 50+ random (TotalCount,
/// PageNumber, PageSize) tuples generated by Bogus with a FIXED seed
/// (<c>Randomizer.Seed = new Random(34567)</c>) — so test runs are
/// deterministic and reproducible.
///
/// INVARIANTS VERIFIED:
///   1. TotalPages == ceil(TotalCount / PageSize) — for any (TotalCount,
///      PageSize) with PageSize ≥ 1.
///   2. HasPreviousPage == (PageNumber > 1).
///   3. HasNextPage == (PageNumber < TotalPages).
///   4. Items.Count ≤ PageSize (the wrapper just stores what's passed in;
///      caller is responsible for taking a page slice — so this test
///      passes it the slice and verifies the bound).
///   5. Page 1 always has HasPreviousPage=false (the leftmost page has no
///      previous page).
///   6. The last page (PageNumber == TotalPages) always has HasNextPage=false.
///   7. Any page beyond the last page (PageNumber > TotalPages) has
///      HasNextPage=false AND HasPreviousPage=true.
/// </summary>
public class PaginatedResultPropertyTests
{
    private const int FixedSeed = 34567;
    private const int SampleCount = 50;



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 50 random (totalCount, pageNumber, pageSize) triples. PageSize ≥ 1
    // (the SUT's TotalPages formula divides by PageSize — would
    // DivideByZeroException if 0). TotalCount in [0, 1000] covers the
    // empty-result case. PageNumber in [1, 100] covers most UI cases.
    public static IEnumerable<object[]> RandomPaginationTriples()
    {
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(0, 1000),     // TotalCount
                faker.Random.Int(1, 100),      // PageNumber
                faker.Random.Int(1, 100)       // PageSize
            })
            .ToList();
    }

    // 50 random (totalCount, pageSize) pairs — used for the TotalPages
    // formula invariant (independent of PageNumber).
    public static IEnumerable<object[]> RandomCountSizePairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(0, 1000),     // TotalCount
                faker.Random.Int(1, 100)      // PageSize
            })
            .ToList();
    }

    // 50 random (totalCount, pageSize) pairs where the page we pick is
    // guaranteed to be page 1 — exercises the HasPreviousPage=false
    // invariant on the leftmost page.
    public static IEnumerable<object[]> RandomFirstPageCases()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(0, 1000),     // TotalCount
                faker.Random.Int(1, 100)      // PageSize
            })
            .ToList();
    }

    // 50 random (totalCount, pageSize) pairs for the LAST-page test. We
    // compute PageNumber = TotalPages inside the test (it depends on the
    // generated totalCount + pageSize).
    public static IEnumerable<object[]> RandomLastPageCases()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 1000),    // TotalCount (≥1 so ≥1 page)
                faker.Random.Int(1, 100)      // PageSize
            })
            .ToList();
    }

    // 50 random (totalCount, pageSize) pairs for the BEYOND-LAST-page test.
    // We compute PageNumber = TotalPages + 1 inside the test.
    public static IEnumerable<object[]> RandomBeyondLastPageCases()
    {
        Randomizer.Seed = new Random(FixedSeed + 4);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 1000),    // TotalCount ≥ 1 so TotalPages ≥ 1
                faker.Random.Int(1, 100)      // PageSize
            })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: TotalPages == ceil(TotalCount / PageSize) — for any random
    // (totalCount, pageSize) with PageSize ≥ 1. The SUT computes this as
    // (int)Math.Ceiling(totalCount / (double)pageSize). The test uses the
    // same formula as the expected value, asserting exact equality (this
    // catches a future refactor that changes the rounding strategy).
    [Theory]
    [MemberData(nameof(RandomCountSizePairs))]
    public void PaginatedResult_TotalPages_IsCeilingDivision_HoldsForRandomSizes(int totalCount, int pageSize)
    {
        // Arrange
        var expectedTotalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
        var items = new int[Math.Min(totalCount, pageSize)];

        // Act
        var result = new PaginatedResult<int>(items, totalCount, 1, pageSize);

        // Assert
        result.TotalPages.Should().Be(expectedTotalPages);
    }

    // Property: HasPreviousPage == (PageNumber > 1) — for any random
    // (totalCount, pageNumber, pageSize). The contract is page-number
    // based; whether the previous page has items is not the wrapper's
    // concern.
    [Theory]
    [MemberData(nameof(RandomPaginationTriples))]
    public void PaginatedResult_HasPreviousPage_EqualsPageNumberGtOne_HoldsForRandomTriples(
        int totalCount, int pageNumber, int pageSize)
    {
        // Arrange + Act
        var result = new PaginatedResult<int>(Array.Empty<int>(), totalCount, pageNumber, pageSize);

        // Assert
        result.HasPreviousPage.Should().Be(pageNumber > 1);
    }

    // Property: HasNextPage == (PageNumber < TotalPages) — for any random
    // (totalCount, pageNumber, pageSize). Symmetric with the previous-page
    // invariant.
    [Theory]
    [MemberData(nameof(RandomPaginationTriples))]
    public void PaginatedResult_HasNextPage_EqualsPageNumberLtTotalPages_HoldsForRandomTriples(
        int totalCount, int pageNumber, int pageSize)
    {
        // Arrange
        var expectedTotalPages = (int)Math.Ceiling(totalCount / (double)pageSize);

        // Act
        var result = new PaginatedResult<int>(Array.Empty<int>(), totalCount, pageNumber, pageSize);

        // Assert
        result.HasNextPage.Should().Be(pageNumber < expectedTotalPages);
    }

    // Property: Items.Count ≤ PageSize — the wrapper doesn't slice items
    // itself (it's the caller's job), so this test passes a correctly-sized
    // slice and verifies the bound holds. Catches a future "Items" overload
    // that loses the bound.
    [Theory]
    [MemberData(nameof(RandomCountSizePairs))]
    public void PaginatedResult_ItemsCount_BoundedByPageSize_HoldsForRandomSizes(int totalCount, int pageSize)
    {
        // Arrange — take the page slice as the caller would. For the FIRST
        // page: take min(pageSize, totalCount) items.
        var itemsOnThisPage = Math.Min(pageSize, totalCount);
        var items = Enumerable.Range(0, itemsOnThisPage).Select(i => i).ToArray();

        // Act
        var result = new PaginatedResult<int>(items, totalCount, 1, pageSize);

        // Assert — the bound holds.
        result.Items.Count.Should().BeLessThanOrEqualTo(result.PageSize);
        result.Items.Count.Should().Be(itemsOnThisPage);
    }

    // Property: Page 1 always has HasPreviousPage=false — for any random
    // (totalCount, pageSize). The leftmost page has no predecessor.
    [Theory]
    [MemberData(nameof(RandomFirstPageCases))]
    public void PaginatedResult_FirstPage_AlwaysHasNoPrevious_HoldsForRandomSizes(int totalCount, int pageSize)
    {
        // Arrange + Act — page 1 of any pagination.
        var result = new PaginatedResult<int>(Array.Empty<int>(), totalCount, 1, pageSize);

        // Assert
        result.HasPreviousPage.Should().BeFalse();
    }

    // Property: The last page (PageNumber == TotalPages) always has
    // HasNextPage=false — for any random (totalCount, pageSize) with
    // totalCount ≥ 1 so that TotalPages ≥ 1.
    [Theory]
    [MemberData(nameof(RandomLastPageCases))]
    public void PaginatedResult_LastPage_AlwaysHasNoNext_HoldsForRandomSizes(int totalCount, int pageSize)
    {
        // Arrange
        var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
        // totalPages ≥ 1 since totalCount ≥ 1.
        var pageNumber = totalPages;

        // Act
        var result = new PaginatedResult<int>(Array.Empty<int>(), totalCount, pageNumber, pageSize);

        // Assert — last page has no successor.
        result.HasNextPage.Should().BeFalse();
    }

    // Property: Any page BEYOND the last page (PageNumber > TotalPages)
    // has HasNextPage=false AND HasPreviousPage=true — for any random
    // (totalCount, pageSize) with totalCount ≥ 1. The SUT does NOT clamp
    // PageNumber, so this case is reachable (UI bugs, off-by-one).
    [Theory]
    [MemberData(nameof(RandomBeyondLastPageCases))]
    public void PaginatedResult_BeyondLastPage_HasNoNextAndHasPrevious_HoldsForRandomSizes(int totalCount, int pageSize)
    {
        // Arrange
        var totalPages = (int)Math.Ceiling(totalCount / (double)pageSize);
        // pageNumber = totalPages + 1 (one beyond the last).
        var pageNumber = totalPages + 1;

        // Act
        var result = new PaginatedResult<int>(Array.Empty<int>(), totalCount, pageNumber, pageSize);

        // Assert — beyond-last page has no next (already past the last)
        // AND has a previous (any pageNumber > 1 has HasPrevious=true).
        result.HasNextPage.Should().BeFalse();
        result.HasPreviousPage.Should().BeTrue();
    }
}
