using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;
using TakOne.SharedKernel.Common;
using Xunit;

namespace TakOne.SharedKernel.Tests.Common;

/// <summary>
/// Property-based / fuzz tests for the <see cref="Result"/> and
/// <see cref="Result{T}"/> types — the operation-outcome monads used as
/// the return type for ALL commands and queries in the Application layer.
///
/// Each test asserts a CONTRACT holds over 50+ random inputs generated by
/// Bogus with a FIXED seed (<c>Randomizer.Seed = new Random(23456)</c>) —
/// so test runs are deterministic and reproducible.
///
/// CONTRACTS VERIFIED:
///   1. Result.Failure(error) always has IsFailure=true, IsSuccess=false, Error=error.
///   2. Result.Success() always has IsSuccess=true, IsFailure=false, Error="" (empty string).
///   3. Result{T}.Success(value) always has IsSuccess=true, Value=value.
///   4. Result{T}.Failure(error) does NOT set Value (Value=default(T) for the type).
///   5. Result.Failure(error) is idempotent — calling it twice with the same error
///      produces two Result instances whose .Error strings are equal.
///   6. Result.Success() with random "call sites" (i.e. parameterless) is invariant
///      — locks the contract that Success takes no args and is the universal OK.
///
/// NOTE — The Result ctor enforces that a successful Result MUST have an
/// empty error string and a failed Result MUST have a non-empty error string.
/// Attempting Success("oops") or Failure("") would itself throw
/// InvalidOperationException, which is NOT what these tests exercise.
/// </summary>
public class ResultPropertyTests
{
    private const int FixedSeed = 23456;
    private const int SampleCount = 50;



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 50 random non-null, non-empty error strings (varied lengths, varied
    // char sets — Unicode + ASCII + punctuation). Used for Failure(error)
    // idempotency and IsFailure tests.
    public static IEnumerable<object[]> RandomErrorStrings()
    {
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Lorem.Sentence(faker.Random.Int(2, 20)) })
            .ToList();
    }

    // 50 random integer values for Result<T>.Success(value) tests.
    public static IEnumerable<object[]> RandomIntegers()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(int.MinValue, int.MaxValue) })
            .ToList();
    }

    // 50 random string values for Result<string>.Success(value) tests.
    public static IEnumerable<object[]> RandomStrings()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Lorem.Sentence(faker.Random.Int(1, 30)) })
            .ToList();
    }

    // 50 random "call indices" — used only as the MemberData shape to drive
    // 50 invocations of Result.Success() (which takes no args). The int
    // itself is not used in the test; it just multiplies the test count.
    public static IEnumerable<object[]> RandomCallIndices()
    {
        // Fixed sequence 0..49 — no need for Bogus.
        return Enumerable.Range(0, SampleCount).Select(i => new object[] { i }).ToList();
    }

    // 50 random (error1, error2) pairs of distinct error strings — used for
    // the Failure-idempotency test (each call returns an equal Error string).
    public static IEnumerable<object[]> RandomErrorPairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Lorem.Sentence(faker.Random.Int(2, 20)),
                faker.Lorem.Sentence(faker.Random.Int(2, 20))
            })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: Result.Failure(error) always yields IsFailure=true,
    // IsSuccess=false, Error=error — for any non-empty random string error.
    [Theory]
    [MemberData(nameof(RandomErrorStrings))]
    public void ResultFailure_AlwaysIsFailure_HoldsForRandomErrors(string error)
    {
        // Arrange + Act
        var result = Result.Failure(error);

        // Assert
        result.IsFailure.Should().BeTrue();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(error);
    }

    // Property: Result.Success() always yields IsSuccess=true, IsFailure=false,
    // Error=string.Empty — for any "call site" (50 random invocations). The
    // random call index parameter exists only to multiply the test count
    // (Result.Success() takes no args).
    [Theory]
    [MemberData(nameof(RandomCallIndices))]
    public void ResultSuccess_AlwaysIsSuccess_HoldsForRandomCalls(int _)
    {
        // Arrange + Act — Success() takes no args; the random index above just
        // drives 50 invocations.
        var result = Result.Success();

        // Assert
        result.IsSuccess.Should().BeTrue();
        result.IsFailure.Should().BeFalse();
        // Per SUT, the success ctor sets Error = string.Empty (NOT null).
        result.Error.Should().Be(string.Empty);
    }

    // Property: Result<T>.Success(value) always yields IsSuccess=true and
    // Value=value — for any random integer value.
    [Theory]
    [MemberData(nameof(RandomIntegers))]
    public void ResultGenericSuccess_AlwaysIsSuccessAndCarriesValue_HoldsForRandomInts(int value)
    {
        // Arrange + Act
        var result = Result<int>.Success(value);

        // Assert
        result.IsSuccess.Should().BeTrue();
        result.IsFailure.Should().BeFalse();
        result.Value.Should().Be(value);
        result.Error.Should().Be(string.Empty);
    }

    // Property: Result<string>.Success(value) always yields IsSuccess=true
    // and Value=value — for any random string value (including non-ASCII).
    [Theory]
    [MemberData(nameof(RandomStrings))]
    public void ResultGenericSuccess_WithStringCarriesValue_HoldsForRandomStrings(string value)
    {
        // Arrange + Act
        var result = Result<string>.Success(value);

        // Assert
        result.IsSuccess.Should().BeTrue();
        result.Value.Should().Be(value);
    }

    // Property: Result<T>.Failure(error) makes Value INACCESSIBLE —
    // accessing Value throws InvalidOperationException (Brutal Code
    // Review v3 finding #16). Previously, Value returned default(T)
    // silently (0 for int, null for string), which let callers
    // propagate 0/null downstream without noticing the failure. The
    // throw makes the footgun loud: callers MUST check IsSuccess first.
    [Theory]
    [MemberData(nameof(RandomErrorStrings))]
    public void ResultGenericFailure_ThrowsOnValueAccess_HoldsForRandomErrors(string error)
    {
        // Arrange + Act — construct both an int and string generic failure.
        var intResult = Result<int>.Failure(error);
        var stringResult = Result<string>.Failure(error);

        // Assert — the failure state is correct, and Value access throws.
        intResult.IsFailure.Should().BeTrue();
        intResult.IsSuccess.Should().BeFalse();
        intResult.Error.Should().Be(error);
        // Accessing Value on a failed Result throws — the caller must
        // check IsSuccess first. The message includes the Error for
        // diagnostics.
        var intAct = () => intResult.Value;
        intAct.Should().Throw<InvalidOperationException>()
            .WithMessage("*Cannot access Value of a failed Result*");

        stringResult.IsFailure.Should().BeTrue();
        stringResult.IsSuccess.Should().BeFalse();
        stringResult.Error.Should().Be(error);
        var stringAct = () => stringResult.Value;
        stringAct.Should().Throw<InvalidOperationException>()
            .WithMessage("*Cannot access Value of a failed Result*");
    }

    // Property: Result.Failure(error) is idempotent — two calls with the
    // same error string produce two distinct Result instances whose .Error
    // values are equal. (Idempotent at the value level, not the reference
    // level — Result is a class, not a struct, so reference equality fails
    // but value equality on .Error holds.)
    [Theory]
    [MemberData(nameof(RandomErrorPairs))]
    public void ResultFailure_ErrorIsIdempotent_HoldsForRandomErrors(string error1, string error2)
    {
        // Arrange + Act — two Failure calls with the SAME first error.
        var result1 = Result.Failure(error1);
        var result2 = Result.Failure(error1);

        // Assert — the .Error strings are equal even though the instances
        // are distinct references (Failure() returns new(...) every call).
        result1.Error.Should().Be(result2.Error);
        result1.Error.Should().Be(error1);

        // Different errors → different .Error values.
        if (error1 != error2)
        {
            var result3 = Result.Failure(error2);
            result3.Error.Should().NotBe(result1.Error);
        }
    }

    // Property: Result.Success() Error is the empty string (NOT null). The
    // Result ctor's success path requires IsSuccess=true AND error to be
    // empty (string.IsNullOrEmpty(error) is the gate). Locks the contract
    // that a successful result NEVER carries an error message.
    [Theory]
    [MemberData(nameof(RandomCallIndices))]
    public void ResultSuccess_ErrorIsEmptyString_HoldsForRandomCalls(int _)
    {
        // Arrange + Act
        var result = Result.Success();

        // Assert — empty string, not null. This is the contract: callers
        // can do result.Error?.Length and never NPE on a success result.
        result.Error.Should().NotBeNull();
        result.Error.Should().Be(string.Empty);
    }
}
