using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using TakOne.SharedKernel.Common;
using TakOne.SharedKernel.ValueObjects;
using Xunit;

namespace TakOne.SharedKernel.Tests.ValueObjects;

/// <summary>
/// Property-based / fuzz tests for the <see cref="Money"/> immutable value
/// object. Each test asserts an algebraic INVARIANT holds over a randomized
/// input space of 50+ cases generated by Bogus with a FIXED seed
/// (<c>Randomizer.Seed = new Random(12345)</c>) — so test runs are
/// deterministic and reproducible.
///
/// INVARIANTS VERIFIED:
///   1. Commutativity of Money addition: a + b == b + a.
///   2. Identity of zero: a + Money.Zero(c) == a.
///   3. Distributivity of multiplication over addition: (a + b) * k == a * k + b * k.
///   4. Money ctor accepts negative amounts (documents the absence of a guard).
///   5. Money ctor rejects currency strings whose length is not 3.
///   6. Money ctor accepts random 3-letter uppercase currency codes.
///   7. Money.Equals is reflexive, symmetric, transitive.
///   8. Money.GetHashCode is consistent (idempotent) and agrees with Equals.
///   9. Money.ToString contains the Amount (F2) and Currency components.
///
/// NOTE — Money's arithmetic surface is OPERATOR-BASED (+, -, *), NOT method-
/// based. There is no Money.Add or Money.Multiply method. The property tests
/// use the operators directly; the invariants hold on operators exactly as
/// they would on named methods.
/// </summary>
public class MoneyPropertyTests
{
    // Bogus drives the randomized input generation. Randomizer.Seed is set
    // once per MemberData generator so each run produces the same 50 cases.
    private const int FixedSeed = 12345;
    private const int SampleCount = 50;
    private static readonly string[] Currencies = { "USD", "IRR", "EUR" };



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 50 random (aAmount, bAmount, currency) triples — a and b share the
    // same currency, which is required for addition.
    public static IEnumerable<object[]> RandomMoneyPairs()
    {
        // Fixed seed → deterministic, reproducible test runs.
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Decimal(0.01m, 1_000_000m),
                faker.Random.Decimal(0.01m, 1_000_000m),
                faker.PickRandom(Currencies)
            })
            .ToList();
    }

    // 50 random (amount, currency) pairs for single-Money invariants.
    public static IEnumerable<object[]> RandomMoneys()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Decimal(0.01m, 1_000_000m),
                faker.PickRandom(Currencies)
            })
            .ToList();
    }

    // 50 random (aAmount, bAmount, currency, multiplier) quadruples for
    // the distributivity invariant. Multiplier is positive int in [1, 1000].
    public static IEnumerable<object[]> RandomMoneyTuplesWithMultiplier()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Decimal(0.01m, 100_000m),
                faker.Random.Decimal(0.01m, 100_000m),
                faker.PickRandom(Currencies),
                faker.Random.Int(1, 1000)
            })
            .ToList();
    }

    // 50 random negative decimal amounts — used to document that the Money
    // ctor does NOT throw on negative amounts (no negative-amount guard).
    public static IEnumerable<object[]> RandomNegativeAmounts()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Decimal(-1_000_000m, -0.01m),
                faker.PickRandom(Currencies)
            })
            .ToList();
    }

    // 50 random currency strings whose length is NOT 3 (lengths 1, 2, 4, 5,
    // made of uppercase ASCII letters) — the ctor MUST reject these.
    public static IEnumerable<object[]> RandomInvalidCurrencyStrings()
    {
        Randomizer.Seed = new Random(FixedSeed + 4);
        var faker = new Faker();
        var lengths = new[] { 1, 2, 4, 5 };
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var len = faker.PickRandom(lengths);
                // Build a random ASCII-letter string of that length.
                var chars = new string(Enumerable.Range(0, len)
                    .Select(_ => faker.PickRandom(Enumerable.Range('A', 26).Select(c => (char)c).ToArray()))
                    .ToArray());
                return new object[] { chars };
            })
            .ToList();
    }

    // 50 random valid 3-letter uppercase currency codes (random letters).
    public static IEnumerable<object[]> RandomValidCurrencyStrings()
    {
        Randomizer.Seed = new Random(FixedSeed + 5);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var chars = new string(Enumerable.Range(0, 3)
                    .Select(_ => faker.PickRandom(Enumerable.Range('A', 26).Select(c => (char)c).ToArray()))
                    .ToArray());
                return new object[] { chars };
            })
            .ToList();
    }

    // 50 random (aAmount, bAmount, cAmount, currency) quadruples for the
    // transitivity invariant — all three Moneys share the same currency
    // and the same amount (constructed from aAmount, so the property test
    // is over the equivalence class {Amount, Currency}).
    public static IEnumerable<object[]> RandomMoneyTriples()
    {
        Randomizer.Seed = new Random(FixedSeed + 6);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Decimal(0.01m, 1_000_000m),
                faker.PickRandom(Currencies)
            })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: commutativity of Money addition — for any two Money
    // instances a, b sharing the same currency, a + b == b + a (and the
    // result's currency equals the inputs' currency).
    [Theory]
    [MemberData(nameof(RandomMoneyPairs))]
    public void MoneyAddition_IsCommutative_HoldsForRandomPairs(decimal aAmount, decimal bAmount, string currency)
    {
        // Arrange — two Moneys with the SAME currency (required by +).
        var a = new Money(aAmount, currency);
        var b = new Money(bAmount, currency);

        // Act — left-to-right then right-to-left addition.
        var leftFirst = a + b;
        var rightFirst = b + a;

        // Assert — both Amount and Currency must match.
        leftFirst.Amount.Should().Be(rightFirst.Amount);
        leftFirst.Currency.Should().Be(rightFirst.Currency);
        leftFirst.Currency.Should().Be(currency.ToUpperInvariant());
    }

    // Property: identity of zero under addition — for any Money a,
    // a + Money.Zero(a.Currency) == a (both Amount and Currency).
    [Theory]
    [MemberData(nameof(RandomMoneys))]
    public void MoneyAddition_WithZero_IsIdentity_HoldsForRandomMoney(decimal amount, string currency)
    {
        // Arrange
        var a = new Money(amount, currency);
        var zero = Money.Zero(currency);

        // Act
        var sum = a + zero;

        // Assert — zero is the additive identity for Money.
        sum.Amount.Should().Be(a.Amount);
        sum.Currency.Should().Be(a.Currency);
        sum.Should().Be(a);
    }

    // Property: distributivity of multiplication over addition —
    // for any a, b (same currency) and any positive integer k:
    //     (a + b) * k == a * k + b * k
    // Decimal equality is exact here because all operations are integer-
    // scale decimals; no rounding tolerance required.
    [Theory]
    [MemberData(nameof(RandomMoneyTuplesWithMultiplier))]
    public void MoneyMultiplication_DistributesOverAddition_HoldsForRandomTuples(
        decimal aAmount, decimal bAmount, string currency, int k)
    {
        // Arrange
        var a = new Money(aAmount, currency);
        var b = new Money(bAmount, currency);

        // Act — compute both sides of the distributive identity.
        var lhs = (a + b) * k;
        var rhs = (a * k) + (b * k);

        // Assert
        lhs.Amount.Should().Be(rhs.Amount);
        lhs.Currency.Should().Be(rhs.Currency);
        lhs.Should().Be(rhs);
    }

    // Property: Money ctor accepts negative amounts (documented absence of
    // a guard). The ctor only validates the CURRENCY, not the amount. For
    // any random negative amount + a valid currency, the ctor MUST succeed
    // and store the negative amount verbatim.
    //
    // This documents a real SUT behavior — if a future refactor adds a
    // negative-amount guard, this test will fail and signal the contract
    // change to the team.
    [Theory]
    [MemberData(nameof(RandomNegativeAmounts))]
    public void MoneyConstructor_AcceptsNegativeAmount_HoldsForRandomNegative(decimal negativeAmount, string currency)
    {
        // Arrange + Act — constructing Money with a negative amount.
        var money = new Money(negativeAmount, currency);

        // Assert — the amount is stored as-is (no abs(), no clamp, no throw).
        money.Amount.Should().Be(negativeAmount);
        money.Currency.Should().Be(currency);
    }

    // Property: Money ctor rejects currency strings whose length is not 3.
    // For any random ASCII-letter string of length 1, 2, 4, or 5, the ctor
    // throws a DomainException with the canonical "must be a 3-letter" message.
    [Theory]
    [MemberData(nameof(RandomInvalidCurrencyStrings))]
    public void MoneyConstructor_RejectsInvalidLengthCurrency_HoldsForRandomStrings(string currency)
    {
        // Arrange + Act
        var act = () => new Money(1m, currency);

        // Assert — the length guard fires regardless of the currency contents.
        act.Should().Throw<DomainException>()
            .WithMessage("Currency must be a 3-letter ISO code.");
    }

    // Property: Money ctor accepts any random 3-letter uppercase ASCII
    // currency code and uppercases it (already upper). For 50 random
    // 3-letter strings, the ctor MUST succeed and Currency MUST equal the
    // input (after ToUpperInvariant — already upper so identity).
    [Theory]
    [MemberData(nameof(RandomValidCurrencyStrings))]
    public void MoneyConstructor_AcceptsValidThreeLetterCurrency_HoldsForRandomStrings(string currency)
    {
        // Arrange + Act
        var money = new Money(1m, currency);

        // Assert — ctor succeeds, Currency equals the uppercased input.
        money.Currency.Should().Be(currency.ToUpperInvariant());
        money.Currency.Length.Should().Be(3);
    }

    // Property: Money equality is reflexive, symmetric, transitive.
    //   - Reflexive: a.Equals(a) is true.
    //   - Symmetric: a == b implies b == a (for any two equal Moneys).
    //   - Transitive: a == b and b == c implies a == c.
    // Three Money instances are constructed from the same (amount, currency)
    // — distinct references, equal values — so the equivalence class is
    // exercised across 50 random (amount, currency) inputs.
    [Theory]
    [MemberData(nameof(RandomMoneyTriples))]
    public void MoneyEquals_IsReflexiveSymmetricTransitive_HoldsForRandomTriples(
        decimal amount, string currency)
    {
        // Arrange — three Money instances all with the same Amount+Currency.
        var a = new Money(amount, currency);
        var b = new Money(amount, currency);
        var c = new Money(amount, currency);

        // Act + Assert — reflexive (use .Equals to avoid the CS1718 self-
        // comparison tautology warning on the operator form).
        a.Equals(a).Should().BeTrue();

        // Symmetric
        a.Equals(b).Should().BeTrue();
        b.Equals(a).Should().BeTrue();
        (a == b).Should().BeTrue();
        (b == a).Should().BeTrue();

        // Transitive
        (a == b).Should().BeTrue();
        (b == c).Should().BeTrue();
        (a == c).Should().BeTrue();
    }

    // Property: Money.GetHashCode is consistent — calling it twice on the
    // same instance returns the same hash, AND equal Money instances
    // (same Amount + Currency) produce the same hash.
    [Theory]
    [MemberData(nameof(RandomMoneys))]
    public void MoneyGetHashCode_IsConsistent_HoldsForRandomMoney(decimal amount, string currency)
    {
        // Arrange
        var a = new Money(amount, currency);
        var b = new Money(amount, currency);

        // Act
        var hash1 = a.GetHashCode();
        var hash2 = a.GetHashCode();
        var hashB = b.GetHashCode();

        // Assert — same instance is idempotent; equal instances agree on hash.
        hash1.Should().Be(hash2);
        hash1.Should().Be(hashB);
    }

    // Property: Money.ToString contains the Amount (formatted F2 — two
    // decimal digits) and the Currency. For any random Money, ToString()
    // MUST contain both the currency code and the amount with 2 decimals.
    [Theory]
    [MemberData(nameof(RandomMoneys))]
    public void MoneyToString_ContainsAmountAndCurrency_HoldsForRandomMoney(decimal amount, string currency)
    {
        // Arrange
        var money = new Money(amount, currency);

        // Act
        var s = money.ToString();

        // Assert — ToString format is "{Amount:F2} {Currency}" (per SUT).
        s.Should().Contain(currency);
        // F2 format produces at least one decimal point + two decimal digits.
        s.Should().Contain(".");
        // The string should start with the Amount formatted to 2 decimals.
        // Use InvariantCulture so the test's expected prefix matches
        // the SUT's output deterministically regardless of the host's
        // CurrentCulture decimal-separator convention.
        var expectedAmountPrefix = amount.ToString("F2", CultureInfo.InvariantCulture);
        s.Should().StartWith(expectedAmountPrefix);
    }
}
