<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageReference Include="WolverineFx" Version="6.21.0" />
    <PackageReference Include="WolverineFx.SqlServer" Version="6.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TakOne.Domain\TakOne.Domain.csproj" />
    <ProjectReference Include="..\TakOne.SharedKernel\TakOne.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Categories\EventHandlers\" />
    <Folder Include="Categories\Queries\" />
    <Folder Include="Products\EventHandlers\" />
    <Folder Include="Products\Queries\" />
  </ItemGroup>

</Project>
