using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using TakOne.Domain.Sales.ValueObjects;
using Xunit;

namespace TakOne.Domain.Tests.Sales;

/// <summary>
/// Property-based / fuzz tests for the <see cref="SaleNumber"/> value
/// object — the globally-unique, Persian-calendar-rendered sale identifier.
///
/// Each test asserts an INVARIANT holds over 50+ random (Year, Sequence)
/// inputs generated by Bogus with a FIXED seed
/// (<c>Randomizer.Seed = new Random(45678)</c>) — so test runs are
/// deterministic and reproducible.
///
/// INVARIANTS VERIFIED:
///   1. Create(year, seq) always succeeds for any year in [MinPersianYear,
///      MaxPersianYear] and any seq in [MinSequence, MaxSequence].
///   2. Create(year, seq).Value always starts with the "INT-" prefix.
///   3. Create(year, seq).Value contains the Persian-digit rendering of the
///      year (e.g. 1403 → ۱۴۰۳).
///   4. Create with year below MinPersianYear throws ArgumentException.
///   5. Create with year above MaxPersianYear throws ArgumentException.
///   6. Create with seq below MinSequence throws ArgumentException.
///   7. Create with seq above MaxSequence throws ArgumentException.
///   8. SaleNumber equality + hash consistency: two Create calls with the
///      same (year, seq) yield equal SaleNumber instances with equal hashes.
///
/// DISCOVERY: The task spec said Create throws DomainException for out-of-
/// range year/sequence. The actual SUT throws ArgumentException (a BCL
/// exception, not the domain exception). This is intentional — the
/// SaleNumber ctor validates BOUNDS, not a domain rule; the application
/// layer is responsible for surfacing a friendly error message via the
/// SaleNumberErrors map. Tests assert ArgumentException, not DomainException.
///
/// DISCOVERY: The task spec said "There's likely a Parse(string) method
/// too — round-trips via Parse". There is NO Parse method on SaleNumber.
/// The Value property is one-way (Persian-digit rendering for display);
/// the inverse (Persian-digit string → SaleNumber) is not provided. The
/// round-trip test was therefore dropped; an additional equality-and-hash
/// test substitutes for it.
/// </summary>
public class SaleNumberPropertyTests
{
    private const int FixedSeed = 45678;
    private const int SampleCount = 50;



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 50 random (year, seq) pairs in the VALID range.
    public static IEnumerable<object[]> RandomValidYearSeqPairs()
    {
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(SaleNumber.MinPersianYear, SaleNumber.MaxPersianYear),
                faker.Random.Int(SaleNumber.MinSequence, SaleNumber.MaxSequence)
            })
            .ToList();
    }

    // 50 random years below MinPersianYear (in [1, 1299]).
    public static IEnumerable<object[]> RandomYearsBelowMin()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(1, SaleNumber.MinPersianYear - 1) })
            .ToList();
    }

    // 50 random years above MaxPersianYear (in [1501, 9999]).
    public static IEnumerable<object[]> RandomYearsAboveMax()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(SaleNumber.MaxPersianYear + 1, 9999) })
            .ToList();
    }

    // 50 random sequences below MinSequence (in [-1000, 0]).
    public static IEnumerable<object[]> RandomSeqsBelowMin()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(-1000, 0) })
            .ToList();
    }

    // 50 random sequences above MaxSequence (in [100_000_000, 1_000_000_000]).
    public static IEnumerable<object[]> RandomSeqsAboveMax()
    {
        Randomizer.Seed = new Random(FixedSeed + 4);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[] { faker.Random.Int(100_000_000, 1_000_000_000) })
            .ToList();
    }

    // 50 random valid (year, seq) pairs for the equality-and-hash test —
    // reused across two distinct Create() calls to assert value equality.
    public static IEnumerable<object[]> RandomValidPairsForEquality()
    {
        Randomizer.Seed = new Random(FixedSeed + 5);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(SaleNumber.MinPersianYear, SaleNumber.MaxPersianYear),
                faker.Random.Int(SaleNumber.MinSequence, SaleNumber.MaxSequence)
            })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: Create(year, seq) always succeeds for any (year, seq) in
    // the valid range — the ctor does not throw. Returns a SaleNumber with
    // matching Year and Sequence properties.
    [Theory]
    [MemberData(nameof(RandomValidYearSeqPairs))]
    public void SaleNumberCreate_WithValidYearAndSeq_AlwaysSucceeds_HoldsForRandomPairs(int year, int seq)
    {
        // Arrange + Act — Create is a static factory; throws on out-of-range.
        var number = SaleNumber.Create(year, seq);

        // Assert
        number.Year.Should().Be(year);
        number.Sequence.Should().Be(seq);
    }

    // Property: Create(year, seq).Value always starts with the "INT-"
    // prefix — for any valid (year, seq). The prefix is a constant
    // ("INT" = "Internal"), and the format is "INT-{year}-{seq:D8}".
    [Theory]
    [MemberData(nameof(RandomValidYearSeqPairs))]
    public void SaleNumberCreate_Value_AlwaysStartsWithIntPrefix_HoldsForRandomPairs(int year, int seq)
    {
        // Arrange + Act
        var value = SaleNumber.Create(year, seq).Value;

        // Assert — the prefix is fixed; the format always begins with it.
        value.Should().StartWith($"{SaleNumber.Prefix}-");
        value.Should().StartWith("INT-");
    }

    // Property: Create(year, seq).Value contains the Persian-digit
    // rendering of the year — for any valid year. The mapping is
    // '0'→'۰'...'9'→'۹' (U+06F0..U+06F9). So year 1403 renders as ۱۴۰۳.
    [Theory]
    [MemberData(nameof(RandomValidYearSeqPairs))]
    public void SaleNumberCreate_Value_ContainsPersianDigitYear_HoldsForRandomPairs(int year, int seq)
    {
        // Arrange — pre-compute the expected Persian-digit year string.
        var persianDigits = new[] { '۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹' };
        // Use InvariantCulture for the digit conversion so the test
        // is deterministic regardless of the host's CurrentCulture (some
        // cultures, e.g. ar-SA, render int.ToString() with non-ASCII
        // digits, which would break the c - '0' index math below).
        var expectedPersianYear = new string(year.ToString(CultureInfo.InvariantCulture).Select(c => persianDigits[c - '0']).ToArray());

        // Act
        var value = SaleNumber.Create(year, seq).Value;

        // Assert — the year's Persian-digit rendering appears as a segment.
        value.Should().Contain(expectedPersianYear);
    }

    // Property: Create with year below MinPersianYear always throws
    // ArgumentException — for any random year in [1, 1299]. The error
    // message references the supported range.
    [Theory]
    [MemberData(nameof(RandomYearsBelowMin))]
    public void SaleNumberCreate_WithYearBelowMin_AlwaysThrows_HoldsForRandomYears(int year)
    {
        // Arrange + Act
        var act = () => SaleNumber.Create(year, SaleNumber.MinSequence);

        // Assert — ArgumentException (not DomainException — see class doc).
        act.Should().Throw<ArgumentException>()
            .WithMessage($"Persian year {year} is out of the supported range*");
    }

    // Property: Create with year above MaxPersianYear always throws
    // ArgumentException — for any random year in [1501, 9999].
    [Theory]
    [MemberData(nameof(RandomYearsAboveMax))]
    public void SaleNumberCreate_WithYearAboveMax_AlwaysThrows_HoldsForRandomYears(int year)
    {
        // Arrange + Act
        var act = () => SaleNumber.Create(year, SaleNumber.MinSequence);

        // Assert
        act.Should().Throw<ArgumentException>()
            .WithMessage($"Persian year {year} is out of the supported range*");
    }

    // Property: Create with sequence below MinSequence always throws
    // ArgumentException — for any random seq in [-1000, 0]. The error
    // message references the supported range and the 8-digit format limit.
    [Theory]
    [MemberData(nameof(RandomSeqsBelowMin))]
    public void SaleNumberCreate_WithSeqBelowMin_AlwaysThrows_HoldsForRandomSeqs(int seq)
    {
        // Arrange + Act — use a valid year so only the seq guard fires.
        var act = () => SaleNumber.Create(SaleNumber.MinPersianYear, seq);

        // Assert
        act.Should().Throw<ArgumentException>()
            .WithMessage($"Sale sequence {seq} is out of the supported range*");
    }

    // Property: Create with sequence above MaxSequence always throws
    // ArgumentException — for any random seq in [100_000_000, 1_000_000_000].
    // The error message references the 8-digit format limit (D8 can hold
    // up to 99_999_999).
    [Theory]
    [MemberData(nameof(RandomSeqsAboveMax))]
    public void SaleNumberCreate_WithSeqAboveMax_AlwaysThrows_HoldsForRandomSeqs(int seq)
    {
        // Arrange + Act — valid year, only the seq guard fires.
        var act = () => SaleNumber.Create(SaleNumber.MinPersianYear, seq);

        // Assert
        act.Should().Throw<ArgumentException>()
            .WithMessage($"Sale sequence {seq} is out of the supported range*");
    }

    // Property: Two Create calls with the same (year, seq) yield equal
    // SaleNumber instances with equal hash codes — value-object semantics.
    // This substitutes the spec's "round-trip via Parse" test, which can't
    // be written because SaleNumber has no Parse method.
    [Theory]
    [MemberData(nameof(RandomValidPairsForEquality))]
    public void SaleNumberCreate_EqualityAndHashConsistency_HoldsForRandomPairs(int year, int seq)
    {
        // Arrange — two distinct Create calls with the same (year, seq).
        var a = SaleNumber.Create(year, seq);
        var b = SaleNumber.Create(year, seq);

        // Act + Assert — value equality: a == b, hash(a) == hash(b).
        a.Should().Be(b);
        (a == b).Should().BeTrue();
        a.GetHashCode().Should().Be(b.GetHashCode());
    }
}
