using Bogus;
using FluentAssertions;
using System;
using System.Collections.Generic;
using System.Linq;
using TakOne.Domain.Sales.Entities;
using TakOne.Domain.Sales.Enums;
using TakOne.Domain.Sales.ValueObjects;
using TakOne.SharedKernel.Common;
using TakOne.SharedKernel.ValueObjects;
using TakOne.Testing;
using Xunit;

namespace TakOne.Domain.Tests.Sales;

/// <summary>
/// Property-based / fuzz tests for the <see cref="Sale"/> aggregate root.
///
/// Each test asserts an aggregate INVARIANT holds over 30+ random inputs
/// (line counts, quantities, unit prices) generated by Bogus with a FIXED
/// seed (<c>Randomizer.Seed = new Random(56789)</c>) — so test runs are
/// deterministic and reproducible.
///
/// INVARIANTS VERIFIED:
///   1. Sale.Total.Amount == Σ (qi × pi) for any set of N line items with
///      the same currency — i.e. the aggregate's Total is the algebraic
///      sum of line GrossTotals.
///   2. AddLineItem then RemoveLineItem restores Total to the pre-add
///      value — invariant under add+remove cycles.
///   3. UpdateLineItemQuantity recomputes Total: Total.Amount == newQty
///      × unitPrice.Amount.
///   4. AddLineItem with quantity > purchaseLimit throws DomainException.
///   5. AddLineItem with quantity ≤ purchaseLimit succeeds (no throw).
///   6. Submit transitions Status from Draft to Pending, sets SaleNumber
///      and SubmittedAtUtc ≈ UtcNow.
///   7. Submit on an already-Submitted Sale throws DomainException.
///   8. Approve on a Pending Sale transitions Status to Approved + sets
///      ApprovedByUserId + ApprovedAtUtc ≈ UtcNow.
///   9. Cancel on an already-Cancelled Sale throws DomainException.
///
/// DISCOVERY: The task spec's signature for AddLineItem was
///   (productId, productName, unitPrice: Money, quantity: int, discount: Money?, purchaseLimit: int?)
/// — the actual SUT signature is
///   (productId, productName, quantity: int, unitPrice: Money, purchaseLimit: int? = null)
/// with quantity BEFORE unitPrice and NO discount parameter. SaleLineItem
/// has no Discount field; GrossTotal = Quantity * UnitPrice; Sale.Total =
/// Σ line.GrossTotal (no NetTotal, no discount subtraction).
/// </summary>
public class SaleAggregatePropertyTests
{
    private const int FixedSeed = 56789;
    private const int SampleCount = 30;



    // =======================================================================
    //                          MEMBER-DATA GENERATORS
    // =======================================================================

    // 30 random (n, currency) pairs where N is the line count [1, 20] and
    // currency is one of the supported codes. The line-level randomization
    // (qty, price) is done INSIDE the test method so each iteration sees a
    // distinct seed-driven sequence.
    public static IEnumerable<object[]> RandomLineCounts()
    {
        Randomizer.Seed = new Random(FixedSeed);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 20),                       // N line items
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }) // shared currency
            })
            .ToList();
    }

    // 30 random (quantity, unitPriceAmount, currency) triples for the
    // add+remove restore invariant. Quantity in [1, 100], price in
    // [1m, 1000m].
    public static IEnumerable<object[]> RandomAddRemoveTriples()
    {
        Randomizer.Seed = new Random(FixedSeed + 1);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 100),                       // quantity
                faker.Random.Decimal(1m, 1000m),                // unitPrice amount
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }) // currency
            })
            .ToList();
    }

    // 30 random (initialQty, newQty, price, currency) quadruples for the
    // UpdateLineItemQuantity invariant.
    public static IEnumerable<object[]> RandomUpdateQuads()
    {
        Randomizer.Seed = new Random(FixedSeed + 2);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 100),                       // initialQty
                faker.Random.Int(1, 100),                       // newQty
                faker.Random.Decimal(1m, 1000m),                // unitPrice
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }) // currency
            })
            .ToList();
    }

    // 30 random (quantity, purchaseLimit) pairs where quantity EXCEEDS the
    // purchase limit (so AddLineItem must throw). For the limit-violation
    // invariant.
    public static IEnumerable<object[]> RandomOverLimitPairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 3);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var limit = faker.Random.Int(1, 50);
                // qty strictly greater than limit — must throw.
                var qty = faker.Random.Int(limit + 1, limit + 100);
                return new object[] { qty, limit };
            })
            .ToList();
    }

    // 30 random (quantity, purchaseLimit) pairs where quantity is AT OR
    // BELOW the limit (so AddLineItem must succeed).
    public static IEnumerable<object[]> RandomUnderLimitPairs()
    {
        Randomizer.Seed = new Random(FixedSeed + 4);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ =>
            {
                var limit = faker.Random.Int(1, 50);
                // qty strictly less than OR equal to limit — must succeed.
                var qty = faker.Random.Int(1, limit);
                return new object[] { qty, limit };
            })
            .ToList();
    }

    // 30 random (quantity, unitPriceAmount, currency) triples for the
    // Submit-from-Draft and Submit-twice-throws tests. Quantity in [1, 100],
    // price in [1m, 1000m].
    public static IEnumerable<object[]> RandomSubmitTriples()
    {
        Randomizer.Seed = new Random(FixedSeed + 5);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 100),                       // quantity
                faker.Random.Decimal(1m, 1000m),                // unitPrice
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }) // currency
            })
            .ToList();
    }

    // 30 random (quantity, unitPriceAmount, currency, approverUserId) quads
    // for the Approve invariant. Approver is a non-Empty Guid.
    public static IEnumerable<object[]> RandomApproveQuads()
    {
        Randomizer.Seed = new Random(FixedSeed + 6);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 100),                       // quantity
                faker.Random.Decimal(1m, 1000m),                // unitPrice
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }), // currency
                Guid.NewGuid()                                  // approverUserId (non-Empty)
            })
            .ToList();
    }

    // 30 random (quantity, unitPriceAmount, currency, cancellerUserId,
    // reason) pentads for the Cancel-on-Cancelled invariant.
    public static IEnumerable<object[]> RandomCancelPentads()
    {
        Randomizer.Seed = new Random(FixedSeed + 7);
        var faker = new Faker();
        return Enumerable.Range(0, SampleCount)
            .Select(_ => new object[]
            {
                faker.Random.Int(1, 100),                       // quantity
                faker.Random.Decimal(1m, 1000m),                // unitPrice
                faker.PickRandom(new[] { "USD", "IRR", "EUR" }), // currency
                Guid.NewGuid(),                                 // cancellerUserId
                faker.Lorem.Sentence(faker.Random.Int(2, 20))   // reason
            })
            .ToList();
    }



    // =======================================================================
    //                          PROPERTY TESTS
    // =======================================================================

    // Property: Sale.Total.Amount == Σ (qi × pi) for any set of N line
    // items with the same currency — the aggregate's Total is the
    // algebraic sum of line GrossTotals (each = Quantity × UnitPrice).
    [Theory]
    [MemberData(nameof(RandomLineCounts))]
    public void SaleTotal_EqualsSumOfLineGrossTotals_HoldsForRandomLineCounts(int n, string currency)
    {
        // Arrange — a fresh draft Sale, plus N random (qty, price) pairs.
        var sale = BuildDraftSale();
        // Per-iteration deterministic faker: pick a seed derived from
        // (FixedSeed, n, currency) so each (n, currency) tuple sees a
        // distinct but reproducible random sequence.
        var faker = new Faker();
        faker.Random = new Randomizer(FixedSeed + n * 7 + currency.GetHashCode());
        var lines = Enumerable.Range(0, n).Select(_ => new
        {
            ProductId = Guid.NewGuid(),
            Qty = faker.Random.Int(1, 100),
            Price = faker.Random.Decimal(1m, 1000m)
        }).ToList();
        var expectedTotal = lines.Sum(l => l.Qty * l.Price);

        // Act — add each line; Total recomputes after each AddLineItem.
        foreach (var line in lines)
        {
            sale.AddLineItem(line.ProductId, $"Product-{line.ProductId:N}",
                line.Qty, new Money(line.Price, currency));
        }

        // Assert — Total.Amount == Σ qi × pi (same currency on all lines).
        sale.Total.Amount.Should().Be(expectedTotal);
        sale.Total.Currency.Should().Be(currency);
        sale.LineItems.Count.Should().Be(n);
    }

    // Property: AddLineItem then RemoveLineItem restores Sale.Total to the
    // pre-add value — the add+remove cycle is invariant under Total. This
    // catches a future bug where RemoveLineItem fails to call RecalculateTotal
    // or recomputes it differently than the add path.
    [Theory]
    [MemberData(nameof(RandomAddRemoveTriples))]
    public void SaleAddLineItemThenRemove_RestoresTotal_HoldsForRandomTriples(
        int qty, decimal priceAmount, string currency)
    {
        // Arrange — fresh draft Sale; Total starts at Money.Zero("IRR").
        var sale = BuildDraftSale();
        var beforeAddTotalAmount = sale.Total.Amount;

        // Act — add a line, capture Total after add, then remove the same line.
        var productId = Guid.NewGuid();
        sale.AddLineItem(productId, $"Product-{productId:N}", qty, new Money(priceAmount, currency));
        var afterAddTotal = sale.Total.Amount;
        var lineItemId = sale.LineItems.Single().Id;
        sale.RemoveLineItem(lineItemId);

        // Assert — Total restored to its pre-add value (Money.Zero("IRR")).
        sale.Total.Amount.Should().Be(beforeAddTotalAmount);
        sale.LineItems.Should().BeEmpty();
        // The after-add Total proves the add actually changed state.
        afterAddTotal.Should().Be(qty * priceAmount);
    }

    // Property: UpdateLineItemQuantity recomputes Sale.Total — after a
    // quantity update, Sale.Total.Amount == newQty × unitPrice.Amount.
    [Theory]
    [MemberData(nameof(RandomUpdateQuads))]
    public void SaleUpdateLineItemQuantity_RecomputesTotal_HoldsForRandomQuads(
        int initialQty, int newQty, decimal priceAmount, string currency)
    {
        // Arrange — fresh draft Sale with one line at (initialQty, price).
        var sale = BuildDraftSale();
        var productId = Guid.NewGuid();
        sale.AddLineItem(productId, $"Product-{productId:N}", initialQty, new Money(priceAmount, currency));
        var lineItemId = sale.LineItems.Single().Id;

        // Act — update the line's quantity to newQty.
        sale.UpdateLineItemQuantity(lineItemId, newQty);

        // Assert — Total == newQty × priceAmount (the only line).
        sale.Total.Amount.Should().Be(newQty * priceAmount);
        sale.LineItems.Single().Quantity.Should().Be(newQty);
    }

    // Property: AddLineItem with quantity > purchaseLimit throws
    // DomainException — for any random (qty, limit) where qty > limit.
    [Theory]
    [MemberData(nameof(RandomOverLimitPairs))]
    public void SaleAddLineItem_WithQuantityOverPurchaseLimit_Throws_HoldsForRandomPairs(int qty, int limit)
    {
        // Arrange — fresh draft Sale.
        var sale = BuildDraftSale();

        // Act
        var act = () => sale.AddLineItem(Guid.NewGuid(), "OverLimit Product", qty,
            new Money(10m, "USD"), purchaseLimit: limit);

        // Assert — the aggregate enforces the limit per-product on the
        // first AddLineItem (not just on increments).
        act.Should().Throw<DomainException>()
            .WithMessage($"Purchase limit exceeded for product*{limit}*, requested: {qty}.*");
    }

    // Property: AddLineItem with quantity ≤ purchaseLimit succeeds (no
    // throw) — for any random (qty, limit) where 1 ≤ qty ≤ limit. The
    // resulting line carries the requested Quantity.
    [Theory]
    [MemberData(nameof(RandomUnderLimitPairs))]
    public void SaleAddLineItem_WithQuantityAtOrUnderPurchaseLimit_Succeeds_HoldsForRandomPairs(int qty, int limit)
    {
        // Arrange
        var sale = BuildDraftSale();

        // Act
        sale.AddLineItem(Guid.NewGuid(), "UnderLimit Product", qty,
            new Money(10m, "USD"), purchaseLimit: limit);

        // Assert — line was added; Total reflects it; no exception thrown.
        sale.LineItems.Should().ContainSingle();
        sale.LineItems.Single().Quantity.Should().Be(qty);
    }

    // Property: Submit transitions Status from Draft to Pending + sets
    // SaleNumber + sets SubmittedAtUtc ≈ UtcNow — for any random
    // (qty, price, currency) that yields a positive-Total Sale.
    [Theory]
    [MemberData(nameof(RandomSubmitTriples))]
    public void SaleSubmit_TransitionsDraftToPending_HoldsForRandomTriples(
        int qty, decimal priceAmount, string currency)
    {
        // Arrange — draft Sale with one line (positive total → Submit OK).
        var sale = BuildDraftSale();
        sale.AddLineItem(Guid.NewGuid(), "Submittable Product", qty, new Money(priceAmount, currency));
        var before = DateTime.UtcNow;
        var saleNumber = SaleNumber.Create(1403, 42);

        // Act
        sale.Submit(saleNumber);
        var after = DateTime.UtcNow;

        // Assert — status moved Draft → Pending; SaleNumber + SubmittedAtUtc set.
        sale.Status.Should().Be(SaleStatus.Pending);
        sale.SaleNumber.Should().NotBeNull();
        sale.SaleNumber.Should().Be(saleNumber);
        sale.SubmittedAtUtc.Should().NotBeNull();
        sale.SubmittedAtUtc!.Value.Should().BeOnOrAfter(before);
        sale.SubmittedAtUtc!.Value.Should().BeOnOrBefore(after);
    }

    // Property: Submit on an already-Submitted Sale throws DomainException
    // — for any random (qty, price, currency) that yields a positive-Total
    // Sale. Submit is a one-shot state transition; calling it twice is a
    // domain-rule violation.
    [Theory]
    [MemberData(nameof(RandomSubmitTriples))]
    public void SaleSubmit_OnAlreadySubmitted_Throws_HoldsForRandomTriples(
        int qty, decimal priceAmount, string currency)
    {
        // Arrange — submitted Sale.
        var sale = BuildDraftSale();
        sale.AddLineItem(Guid.NewGuid(), "Submittable Product", qty, new Money(priceAmount, currency));
        sale.Submit(SaleNumber.Create(1403, 42));

        // Act — second Submit on a non-Draft Sale.
        var act = () => sale.Submit(SaleNumber.Create(1403, 43));

        // Assert — EnsureDraft() fires before the rest of Submit's body.
        act.Should().Throw<DomainException>()
            .WithMessage($"Cannot modify line items of a sale that is not in Draft. Current status: 'Pending'.");
    }

    // Property: Approve on a Pending Sale transitions Status to Approved +
    // sets ApprovedByUserId + sets ApprovedAtUtc ≈ UtcNow — for any random
    // (qty, price, currency, approverUserId) with non-Empty approver.
    [Theory]
    [MemberData(nameof(RandomApproveQuads))]
    public void SaleApprove_TransitionsPendingToApproved_HoldsForRandomQuads(
        int qty, decimal priceAmount, string currency, Guid approverUserId)
    {
        // Arrange — pending Sale.
        var sale = BuildDraftSale();
        sale.AddLineItem(Guid.NewGuid(), "Approvable Product", qty, new Money(priceAmount, currency));
        sale.Submit(SaleNumber.Create(1403, 42));
        var before = DateTime.UtcNow;

        // Act
        sale.Approve(approverUserId);
        var after = DateTime.UtcNow;

        // Assert — status Pending → Approved; audit fields populated.
        sale.Status.Should().Be(SaleStatus.Approved);
        sale.ApprovedByUserId.Should().Be(approverUserId);
        sale.ApprovedAtUtc.Should().NotBeNull();
        sale.ApprovedAtUtc!.Value.Should().BeOnOrAfter(before);
        sale.ApprovedAtUtc!.Value.Should().BeOnOrBefore(after);
    }

    // Property: Cancel on an already-Cancelled Sale throws DomainException
    // — for any random (qty, price, currency, cancellerUserId, reason).
    // The first Cancel transitions Pending → Cancelled; the second hits the
    // EnsureCancellable() "already cancelled" guard.
    [Theory]
    [MemberData(nameof(RandomCancelPentads))]
    public void SaleCancel_OnAlreadyCancelled_Throws_HoldsForRandomPentads(
        int qty, decimal priceAmount, string currency, Guid cancellerUserId, string reason)
    {
        // Arrange — submit then cancel once to reach Cancelled status.
        var sale = BuildDraftSale();
        sale.AddLineItem(Guid.NewGuid(), "Cancellable Product", qty, new Money(priceAmount, currency));
        sale.Submit(SaleNumber.Create(1403, 42));
        sale.Cancel(cancellerUserId, reason);
        sale.Status.Should().Be(SaleStatus.Cancelled);

        // Act — second Cancel on an already-Cancelled Sale.
        var act = () => sale.Cancel(cancellerUserId, reason);

        // Assert — EnsureCancellable() throws the "already cancelled" message.
        act.Should().Throw<DomainException>()
            .WithMessage("This sale is already cancelled.");
    }



    // =======================================================================
    //                          PRIVATE HELPERS
    // =======================================================================

    // Build a draft Sale using the well-known TestValues constants.
    private static Sale BuildDraftSale() => Sale.Create(
        customerId: TestValues.CustomerId,
        customerName: "Alice Customer",
        createdByUserId: TestValues.CreatedByUserId,
        createdByName: "Alice Creator");
}
